# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simulation.proto',
  package='GeminiOSPInterface',
  syntax='proto3',
  serialized_options=b'\n\034autoferry.clients.simulationB\nsimulationP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10simulation.proto\x12\x12GeminiOSPInterface\"4\n\x04Pose\x12\r\n\x05north\x18\x01 \x01(\x02\x12\x0c\n\x04\x65\x61st\x18\x02 \x01(\x02\x12\x0f\n\x07heading\x18\x03 \x01(\x02\"\\\n\x0bStepRequest\x12-\n\x0bVesselPoses\x18\x01 \x03(\x0b\x32\x18.GeminiOSPInterface.Pose\x12\x0c\n\x04time\x18\x02 \x01(\x02\x12\x10\n\x08stepSize\x18\x03 \x01(\x02\"\x1f\n\x0cStepResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"#\n\x13SetStartTimeRequest\x12\x0c\n\x04time\x18\x01 \x01(\t\"\'\n\x14SetStartTimeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xc0\x01\n\nSimulation\x12M\n\x06\x44oStep\x12\x1f.GeminiOSPInterface.StepRequest\x1a .GeminiOSPInterface.StepResponse\"\x00\x12\x63\n\x0cSetStartTime\x12\'.GeminiOSPInterface.SetStartTimeRequest\x1a(.GeminiOSPInterface.SetStartTimeResponse\"\x00\x42\x32\n\x1c\x61utoferry.clients.simulationB\nsimulationP\x01\xa2\x02\x03HLWb\x06proto3'
)




_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='GeminiOSPInterface.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='north', full_name='GeminiOSPInterface.Pose.north', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='east', full_name='GeminiOSPInterface.Pose.east', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heading', full_name='GeminiOSPInterface.Pose.heading', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=92,
)


_STEPREQUEST = _descriptor.Descriptor(
  name='StepRequest',
  full_name='GeminiOSPInterface.StepRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='VesselPoses', full_name='GeminiOSPInterface.StepRequest.VesselPoses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='GeminiOSPInterface.StepRequest.time', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stepSize', full_name='GeminiOSPInterface.StepRequest.stepSize', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=186,
)


_STEPRESPONSE = _descriptor.Descriptor(
  name='StepResponse',
  full_name='GeminiOSPInterface.StepResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='GeminiOSPInterface.StepResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=219,
)


_SETSTARTTIMEREQUEST = _descriptor.Descriptor(
  name='SetStartTimeRequest',
  full_name='GeminiOSPInterface.SetStartTimeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='GeminiOSPInterface.SetStartTimeRequest.time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=256,
)


_SETSTARTTIMERESPONSE = _descriptor.Descriptor(
  name='SetStartTimeResponse',
  full_name='GeminiOSPInterface.SetStartTimeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='GeminiOSPInterface.SetStartTimeResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=297,
)

_STEPREQUEST.fields_by_name['VesselPoses'].message_type = _POSE
DESCRIPTOR.message_types_by_name['Pose'] = _POSE
DESCRIPTOR.message_types_by_name['StepRequest'] = _STEPREQUEST
DESCRIPTOR.message_types_by_name['StepResponse'] = _STEPRESPONSE
DESCRIPTOR.message_types_by_name['SetStartTimeRequest'] = _SETSTARTTIMEREQUEST
DESCRIPTOR.message_types_by_name['SetStartTimeResponse'] = _SETSTARTTIMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), {
  'DESCRIPTOR' : _POSE,
  '__module__' : 'simulation_pb2'
  # @@protoc_insertion_point(class_scope:GeminiOSPInterface.Pose)
  })
_sym_db.RegisterMessage(Pose)

StepRequest = _reflection.GeneratedProtocolMessageType('StepRequest', (_message.Message,), {
  'DESCRIPTOR' : _STEPREQUEST,
  '__module__' : 'simulation_pb2'
  # @@protoc_insertion_point(class_scope:GeminiOSPInterface.StepRequest)
  })
_sym_db.RegisterMessage(StepRequest)

StepResponse = _reflection.GeneratedProtocolMessageType('StepResponse', (_message.Message,), {
  'DESCRIPTOR' : _STEPRESPONSE,
  '__module__' : 'simulation_pb2'
  # @@protoc_insertion_point(class_scope:GeminiOSPInterface.StepResponse)
  })
_sym_db.RegisterMessage(StepResponse)

SetStartTimeRequest = _reflection.GeneratedProtocolMessageType('SetStartTimeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETSTARTTIMEREQUEST,
  '__module__' : 'simulation_pb2'
  # @@protoc_insertion_point(class_scope:GeminiOSPInterface.SetStartTimeRequest)
  })
_sym_db.RegisterMessage(SetStartTimeRequest)

SetStartTimeResponse = _reflection.GeneratedProtocolMessageType('SetStartTimeResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETSTARTTIMERESPONSE,
  '__module__' : 'simulation_pb2'
  # @@protoc_insertion_point(class_scope:GeminiOSPInterface.SetStartTimeResponse)
  })
_sym_db.RegisterMessage(SetStartTimeResponse)


DESCRIPTOR._options = None

_SIMULATION = _descriptor.ServiceDescriptor(
  name='Simulation',
  full_name='GeminiOSPInterface.Simulation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=300,
  serialized_end=492,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoStep',
    full_name='GeminiOSPInterface.Simulation.DoStep',
    index=0,
    containing_service=None,
    input_type=_STEPREQUEST,
    output_type=_STEPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetStartTime',
    full_name='GeminiOSPInterface.Simulation.SetStartTime',
    index=1,
    containing_service=None,
    input_type=_SETSTARTTIMEREQUEST,
    output_type=_SETSTARTTIMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMULATION)

DESCRIPTOR.services_by_name['Simulation'] = _SIMULATION

# @@protoc_insertion_point(module_scope)
